ALTER TABLE users
  MODIFY COLUMN username VARCHAR(255) NOT NULL,
  ADD COLUMN name VARCHAR(100) NULL AFTER email,
  ADD COLUMN phone VARCHAR(20) NULL,
  ADD COLUMN role VARCHAR(20) NULL DEFAULT 'staff';
